# Generated by Django 2.2.1 on 2019-05-22 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scratcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scratcher',
            old_name='descirption',
            new_name='des',
        ),
    ]
